[{"name": "test.test_diamond.Diamond.test_calls", "status": "passed", "message": "", "passed": true, "points": ["p02-13.1"], "backtrace": []}, {"name": "test.test_diamond.Diamond.test_content", "status": "errored", "message": "axis 1 is out of bounds for array of dimension 1", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e13_diamond/test/test_diamond.py\", line 52, in test_content\n    d=diamond(n)\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e13_diamond/src/diamond.py\", line 31, in diamond\n    top = np.concatenate((top_left, top_right), axis = 1)\n"]}, {"name": "test.test_diamond.Diamond.test_shape", "status": "errored", "message": "axis 1 is out of bounds for array of dimension 1", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e13_diamond/test/test_diamond.py\", line 45, in test_shape\n    d=diamond(n)\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e13_diamond/src/diamond.py\", line 31, in diamond\n    top = np.concatenate((top_left, top_right), axis = 1)\n"]}, {"name": "test.test_diamond.Diamond.test_type", "status": "failed", "message": "dtype('float64') != <class 'int'> : Incorrect element type!", "passed": false, "points": ["p02-13.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part02-e13_diamond/test/test_diamond.py\", line 41, in test_type\n    self.assertEqual(d.dtype, int, msg=\"Incorrect element type!\")\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]