[{"name": "test.test_areas_of_shapes.AreasOfShapes.test_empty", "status": "failed", "message": "src.areas_of_shapes.main does not exist!", "passed": false, "points": ["p01-07.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e07_areas_of_shapes/test/test_areas_of_shapes.py\", line 22, in test_empty\n    main()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e07_areas_of_shapes/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_areas_of_shapes.AreasOfShapes.test_many_queries", "status": "failed", "message": "src.areas_of_shapes.main does not exist!", "passed": false, "points": ["p01-07.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e07_areas_of_shapes/test/test_areas_of_shapes.py\", line 41, in test_many_queries\n    main()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e07_areas_of_shapes/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}, {"name": "test.test_areas_of_shapes.AreasOfShapes.test_one_query", "status": "failed", "message": "src.areas_of_shapes.main does not exist!", "passed": false, "points": ["p01-07.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e07_areas_of_shapes/test/test_areas_of_shapes.py\", line 29, in test_one_query\n    main()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part01-e07_areas_of_shapes/tmc/utils.py\", line 11, in fail\n    raise AssertionError(err)\n"]}]