[{"name": "test.test_matrix_power.MatrixPower.test_called", "status": "failed", "message": "Expected 'reduce' to have been called.", "passed": false, "points": ["p03-04.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part03-e04_matrix_power/test/test_matrix_power.py\", line 55, in test_called\n    preduce.assert_called()\n", "  File \"/usr/lib/python3.6/unittest/mock.py\", line 786, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_matrix_power.MatrixPower.test_exponents", "status": "passed", "message": "", "passed": true, "points": ["p03-04.1"], "backtrace": []}, {"name": "test.test_matrix_power.MatrixPower.test_multiply", "status": "errored", "message": "Object arrays are not currently supported", "passed": false, "points": ["p03-04.1"], "backtrace": ["  File \"/usr/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n", "  File \"/home/du_ds/Documents/Git/PythonDataAnalysisCourse/hy-data-analysis-with-python-summer-2019/part03-e04_matrix_power/test/test_matrix_power.py\", line 38, in test_multiply\n    np.testing.assert_array_almost_equal(np.eye(2), a1@a2,\n"]}, {"name": "test.test_matrix_power.MatrixPower.test_one", "status": "passed", "message": "", "passed": true, "points": ["p03-04.1"], "backtrace": []}, {"name": "test.test_matrix_power.MatrixPower.test_zero", "status": "passed", "message": "", "passed": true, "points": ["p03-04.1"], "backtrace": []}]